chore: makefile

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,7 +23,23 @@ jobs:
         node-version: ${{ matrix.node }}
     - name: Install dependencies
       run: npm ci
+    - name: Check Types
+      run: npm run type-check
+    - name: Lint
+      run: make lint
+    - name: Test
+      run: npm run test
+    - name: Verify icon changes
+      run: |
+        cd icons
+        rm -rf jsx
+        rm -rf es5
+        npm run build
+        if [[ -n $(git status -s) ]]; then
+          echo "::error::Generated icons do not match committed icons. Please run \`npm run build\` in the icons directory."
+          exit 1
+        fi
+    - name: Build
+      run: npm run build
     - name: Build Docs
-      # npm swallows errors when using npm run build-docs
-      # see https://github.com/openedx/paragon/issues/3329
-      run: npm run build --workspace=www
+      run: make build-docs
